# -*- coding: utf-8 -*-
"""quick_sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15kI2Gu_8H7wQub3CKw1JQm7n13rXm3eQ
"""

lambda L: [] if L==[] else qsort([x for x in L[1:] if x< L[0]]) + L[0:1] + qsort([x for x in L[1:] if x>=L[0]])

